version: "3.9"
services:
  app:
    build: .
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: 512M
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - 80:8080
      - 8080:8080
  locust:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py -H http://nginx:8080